### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Replacing headers with SPDX-headers for REUSE compliance
* Adding a GH action to check future compliance
* Adding a status badge to the readme

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@zak39 and @StCyr there has been a small amount of files which had an AGPL3(only) header instead of an AGPL3(or-later) header. I expect this has simply be an c&p issue yet wanted to get your feedback/approval that you are fine with the change from AGPL3 to AGPL3+ like all the other files in this repo. Thanks in advance.

**Comment by zak39** [comment]
> @zak39 and @StCyr there has been a small amount of files which had an AGPL3(only) header instead of an AGPL3(or-later) header. I expect this has simply be an c&p issue yet wanted to get your feedback/approval that you are fine with the change from AGPL3 to AGPL3+ like all the other files in this repo. Thanks in advance.

Hi @AndyScherzinger :)

I think it was a copy and paste problem, because I see "Groupfolders" instead of "@license GNU AGPL version 3 or any later version". It's strange :no_mouth: 

Nevertheless, all our files have the `@license GNU AGPL version 3 or any later version` in the header.

We worked on these files from this Nextcloud 23 documentation : https://docs.nextcloud.com/server/23/developer_manual/getting_started/codingguidelines.html .

Our files are : 

- src/Constants.js
- lib/Service/FolderFilter.php *
- lib/Service/ApplicationService.php *
- src/settings/AdminGroupSelect.tsx
- src/settings/SubAdminGroupSelect.tsx

* These files have "Groupfolders" instead of "@license GNU AGPL version 3 or any later version".

I don't think I forgot any other file :thinking: 

I will update these files :+1:

**Comment by StCyr** [comment]
> @zak39 and @StCyr there has been a small amount of files which had an AGPL3(only) header instead of an AGPL3(or-later) header. I expect this has simply be an c&p issue yet wanted to get your feedback/approval that you are fine with the change from AGPL3 to AGPL3+ like all the other files in this repo. Thanks in advance.

No problem for me! Thanks for all your good work! :fire:

**Comment by AndyScherzinger** [comment]
@icewind1991 only 2 cypress tests are failing but they seem unrelated since they also fail on other PRs i.e. https://github.com/nextcloud/groupfolders/actions/runs/10288140194/job/28539422476?pr=3096

**Pull request merged**
