### PR TITLE
fix downloading trashbin items

### PR DESCRIPTION
**Pull request by icewind1991**
The trashbin app makes some assumptions on how trash is stored in the backends to handle the download.

### CODE REVIEW

**Comment by solracsf** [comment]
Will this fix https://github.com/nextcloud/groupfolders/issues/2680 and/or https://github.com/nextcloud/groupfolders/issues/2657 ?

**Review by Pytal — APPROVED** [review]
Works! 💪

**Comment by icewind1991** [comment]
> Will this fix #2680 and/or #2657 ?

I believe it fixes #2680, it works around #2657, but https://github.com/nextcloud/server/pull/42558 is the proper fix for that

**Pull request merged**
