### PR TITLE
Try to return the owner of the mountpoint before returning no owner

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by ChrisanthLederer** [comment]
Hi rullzer,
I'm have manually applied the changes to my Nextcloud 18.0.2 installation. 
This fixes the upload error, but no upload activity is logged and notification email is generated :-(

Now the big problem is that you are not able to delete files that have been uploaded
by an external User (that has been send a folder link).
A Fatal webdav OCP\Files\NotFoundException: CLOUD/10000/test.pdf has no owner 
is raised in /var/www/nextcloud/lib/private/Files/Filesystem.php - line 907
after I changed View.php to throw a NotFoundException (#19978).

Regards
Chris

**Comment by mesiah1970-haydar** [comment]
> Hi rullzer,
> I have manually applied the changes to my Nextcloud 18.0.2 installation.
> This fixes the upload error, but no upload activity is logged and notification email is generated :-(
> 
> Now the big problem is that you are not able to delete files that have been uploaded
> by an external user (that has been send a folder link).
> A Fatal webdav OCP\Files\NotFoundException: CLOUD/10000/test.pdf has no owner
> is raised in /var/www/nextcloud/lib/private/Files/Filesystem.php - line 907
> after I changed View.php to throw a NotFoundException (#19978).
> 
> Regards
> Chris

Hello Chris I just can confirm this: Error, while deleting file.
But the upload error was gone, after I've deactivated the activity app. So I can live without the activity log, but not with error deleting the file

**Comment by mesiah1970-haydar** [comment]
> /backport to stable4

Hello Julius,

ist this related to the issue of 

ChrisanthLederer commented 14 days ago • 

in this conversation??

Haydar

**Pull request merged**
