### PR TITLE
Fix timestamp and rollback of versions

### PR DESCRIPTION
**Pull request by XueSheng-GIT**
Fix https://github.com/nextcloud/groupfolders/issues/2055 and fix https://github.com/nextcloud/groupfolders/issues/2077

File versioning for groupfolders is still broken. I'm not a programmer but after some investigation this change does improve things. This is my first pull request, thus I'm not sure whether this is the right way to go. Feel free to guide me into the right direction! Thanks.

### CODE REVIEW

**Comment by XueSheng-GIT** [comment]
@juliushaertl @ArtificialOwl Any hints how to proceed with this? This is my first pull and I'm a bit lost what else I have to do. Thanks for your support.

**Comment by solracsf** [comment]
Please fix DCO to mark this for review. Thanks 👍

**Comment by solracsf** [comment]
And squash all you commits into one single final and descriptive one ;)

**Comment by XueSheng-GIT** [comment]
@solracsf thanks for your hints! Commits should have been squashed now and DCO seems to be successful now.
Anything else I can do to get this merged?

**Comment by XueSheng-GIT** [comment]
Coding standards check failed because `$version->getRevisionId()` is no int? But actually it is!?

**Comment by solracsf** [comment]
What about:

`$targetMount->getStorage()->touch($targetInternalPath, intval($version->getRevisionId()));`

**Comment by XueSheng-GIT** [comment]
Closing this pull in favour of https://github.com/nextcloud/groupfolders/pull/2543

**Pull request closed without merging**
