### PR TITLE
Fix #801 Folder icon in shared group folder

### LINKED ISSUE #801: Groupfolders do not show folder icon when share a folder with subfolders
Hi, when I share a link folder with subfolders inside in the groupfolders structure, the folder icon do not appear correctly.

imagen

imagen

I tried to solve it creating the path /app/theming/img/core/filetypes and copying the icon from data folder.

1 - sudo -u www-data mkdir /var/www/nextcloud/apps/theming/img/core/filetypes

2 - sudo -u www-data cp /path/to/data/appdata_ocg5dv4z64ej/theming/66/icon-core-filetypes_folder.svg   /var/www/nextcloud/apps/theming/img/core/filetypes/file.svg

it doesn't work, the nextcloud instance starts to work bad.

some idea?

thanks.

### PR DESCRIPTION
**Pull request by JohannesKreuzer**
Always set icon for group folder via ContentLoaded event to have it also in a shared folder.

### CODE REVIEW

**Comment by JohannesKreuzer** [comment]
fixes also #490 & #809

**Comment by JohannesKreuzer** [comment]
@juliushaertl @ChristophWurst is there a chance to get this merged for the next (patch-)release?

**Comment by juliushaertl** [comment]
Good catch, we actually should be able to remove the registration in the file list plugin then as the content loaded event should already cover that part as well.

**Comment by JohannesKreuzer** [comment]
@juliushaertl I submitted an update to the pull request removing the registrtion in the file list plugin as you suggested

**Review by ChristophWurst — APPROVED** [review]
Looks good!

**Comment by juliushaertl** [comment]
Thanks a lot for this. I pushed an updated version to https://github.com/nextcloud/groupfolders/pull/1318 including your commits so we can get this in now, since with the change in loading additional scripts with the new events in Nextcloud 20+ the script was not yet loaded on public share links.

**Pull request closed without merging**
