### PR TITLE
Obtain cacheEntry for created folders and handle errors more gracefully

### PR DESCRIPTION
**Pull request by juliushaertl**
Slightly adjusted version of https://github.com/nextcloud/groupfolders/pull/844 in order to handle possible errors more gracefully. 

This should resolve issues when the mountpoint cache is accessed during creation.

### CODE REVIEW

**Review by rullzer — APPROVED** [review]
:elephant:

**Comment by juliushaertl** [comment]
Waiting for backports of https://github.com/nextcloud/groupfolders/pull/1239 to be merged to avoid another conflict

**Review by icewind1991 — APPROVED** [review]

**Pull request merged**
