### PR TITLE
Feat custom propagator

### PR DESCRIPTION
**Pull request by gbrousse-recia**
## Description
A custom Propagator to fix files updates propagation in nested groupfolders.
Based on branch  `stable25`.
Tested on Nextcloud 25.0.6.
## Related Issue
maybe  #652 and #1787 
## Motivation and Context
We had synchronization issues between the server and the client when the files were in nested groupfolders. After some research, we noticed that the propagation was not done correctly (groupfolders etags unchanged in the filecache table).

### CODE REVIEW

**Comment by kesselb** [comment]
Thanks for your pull request :+1: 

Our usual workflow is to submit a change to branch master first and back port to stable (the latter is done by a bot).

**Comment by juliushaertl** [comment]
Thanks a lot @gbrousse-recia this looks promising, but as @kesselb asked, could you please open a pull request for this towards the master branch?

**Comment by gbrousse-recia** [comment]
> @gbrousse-recia Do you mind if I cherry pick this and open a new PR to the master branch?

@tacruc, Yes, no problem, if you think it is revelant.

**Comment by blizzz** [comment]
closing in favor of #2533, also 25 is EOL

**Pull request closed without merging**
