### PR TITLE
Check if $user is set before calling it

### PR DESCRIPTION
**Pull request by solracsf**
Fix https://github.com/nextcloud/groupfolders/issues/2473

### CODE REVIEW

**Comment by juergen852** [comment]
We experience this problem too.

**Review by juliushaertl — APPROVED** [review]

**Comment by BJKle** [comment]
Is there a release date?

**Comment by fromanm1** [comment]
I found the option scan of gropupfolders didn't work because we just lost 6tb of data, I restore a backup and when I want to rescan the directories I almost have a heart attack.

Thank you for the fix, I really needed.

**Comment by BJKle** [comment]
> Is there a release date?

@solracsf Can you provide an answer? Thank you

**Comment by solracsf** [comment]
No. You can apply the patch manually.

**Comment by quenenni** [comment]
> > Is there a release date?
> 
> No. You can apply the patch manually.

Please, that's not serious.
I updated half of our 500 clouds and now I have lots of cron errors all the time. 
I'm afraid to update the other part.
That's a shitty situation. Nextcloud forced us to update our v24 clouds because of the new aggresive security politic and if I upgrade to v25 or to v26, I have errors with this plugin. :'(

Can you please do a new minor version with this fix.

**Comment by juergen852** [comment]
> No. You can apply the patch manually.
Would love to do that, but how ??
Can you please explain for "normal" admins?

**Comment by BJKle** [comment]
> > > Is there a release date?
> > 
> > 
> > No. You can apply the patch manually.
> 
> Please, that's not serious. I updated half of our 500 clouds and now I have lots of cron errors all the time. I'm afraid to update the other part. That's a shitty situation. Nextcloud forced us to update our v24 clouds because of the new aggresive security politic and if I upgrade to v25 or to v26, I have errors with this plugin. :'(
> 
> Can you please do a new minor version with this fix.

@icewind1991 I‘ve seen you prepared new releases. Could you create one with this patch included? Thanks

**Comment by ChristophWurst** [comment]
> Would love to do that, but how ??

https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#patching-apps

**Comment by solracsf** [comment]
Fix has been released.

**Pull request merged**
