### PR TITLE
Return proper values from AclStorageWrapper

### PR DESCRIPTION
**Pull request by juliushaertl**
Otherwise the methods only return a boolean value instead of the actual result.

### CODE REVIEW

**Comment by icewind1991** [comment]
:see_no_evil: 

(I think I was confused with js where you can use this trick)

**Comment by rullzer** [comment]
@icewind1991 js confuses us all

**Comment by juliushaertl** [comment]
Also took me a while to look at until I god why that was not working properly :wink:

**Comment by wiswedel** [comment]
fixes #551

**Pull request merged**
