### PR TITLE
Fix argument null fatal in case of empty array

### PR DESCRIPTION
**Pull request by Deltachaos**
I found a lot of `TypeError: Argument 2 passed to OCA\\GroupFolders\\ACL\\ACLManager::OCA\\GroupFolders\\ACL\\{closure}() must be of the type array, null given` with `{"file":"/opt/nextcloud-18.0.3/apps/groupfolders/lib/ACL/ACLManager.php","line":122,"function":"array_reduce"}` in my server logs.

I have investigated the issue and found out that the `array_reduce` function of PHP automagically converts an empty array to null.

Example:

```
array_reduce([
    []
], function(array $rules) {
    var_dump($rules);
    return 0;
}) ;
```

Results in:

```
Uncaught TypeError: Argument 1 passed to {closure}() must be of the type array, null given in [...][...]:5
```

And this case is currently not handled in the `ACLManager`. If there are folders passed with no rules, it crashes.

### CODE REVIEW

**Comment by icewind1991** [comment]
I would prefer to solve the issue by fixing the output of `getRules`/`getRulesForPrefix`, adding the `array_filter` logic there

**Comment by Deltachaos** [comment]
@icewind1991 moved it to RuleManager

**Comment by icewind1991** [comment]
:+1:

**Comment by Deltachaos** [comment]
I will move it again ;)

**Comment by pierreozoux** [comment]
@icewind1991 do you have some feedback on the updated version of the PR?

**Comment by Deltachaos** [comment]
@JonathanTreffler will continue to work on this

**Comment by fschrempf** [comment]
Is this PR still valid? If yes can anyone pick it up and get it ready?

**Comment by fschrempf** [comment]
> Is this PR still valid? If yes can anyone pick it up and get it ready?

To answer my own question: #1694 looks like it does already implement the filtering this PR introduces. So this should be fixed in the latest releases.

**Pull request closed without merging**
