### PR TITLE
Add missing exit codes

### LINKED ISSUE #1153: Commands should return an exit code
When running groupfolders:expire I get an error (both via occweb and occ). What looks a little strange to me is the fact that it references something within the mail app. So perhaps also interesting for @ChristophWurst.

Nextcloud 20.0.2 (official Docker)
Groupfolder 8.1.1
Mail 1.7.0

````
Verursacht durchTypeError: Return value of "OCA\GroupFolders\Command\ExpireGroupVersions::execute()" must be of the type int, "null" returned.
/var/www/html/core/Command/Base.php - line 169:
Symfony\Component\Console\Command\Command->run(Symfony\Comp ... {}, OCA\OCCWeb\C ... {})
/var/www/html/custom_apps/mail/vendor/symfony/console/Application.php - line 920:
OC\Core\Command\Base->run(Symfony\Comp ... {}, OCA\OCCWeb\C ... {})
/var/www/html/custom_apps/mail/vendor/symfony/console/Application.php - line 266:
Symfony\Component\Console\Application->doRunCommand(OCA\GroupFol ... {}, Symfony\Comp ... {}, OCA\OCCWeb\C ... {})
/var/www/html/custom_apps/mail/vendor/symfony/console/Application.php - line 142:
Symfony\Component\Console\Application->doRun(Symfony\Comp ... {}, OCA\OCCWeb\C ... {})
/var/www/html/lib/private/Console/Application.php - line 215:
Symfony\Component\Console\Application->run(Symfony\Comp ... {}, OCA\OCCWeb\C ... {})
/var/www/html/custom_apps/occweb/lib/Controller/OccController.php - line 58:
OC\Console\Application->run(Symfony\Comp ... {}, OCA\OCCWeb\C ... {})
/var/www/html/custom_apps/occweb/lib/Controller/OccController.php - line 75:
OCA\OCCWeb\Controller\OccController->run(Symfony\Comp ... {})
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 169:
OCA\OCCWeb\Controller\OccController->cmd("groupfolders:expire")
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 100:
OC\AppFramework\Http\Dispatcher->executeController(OCA\OCCWeb\C ... {}, "cmd")
/var/www/html/lib/private/AppFramework/App.php - line 152:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\OCCWeb\C ... {}, "cmd")
/var/www/html/lib/private/Route/Router.php - line 308:
OC\AppFramework\App::main("OCA\\OCCWeb ... r", "cmd", OC\AppFramew ... {}, { action: nu ... "})
/var/www/html/lib/base.php - line 1008:
OC\Route\Router->match("/apps/occweb/cmd")
/var/www/html/index.php - line 37:
OC::handleRequest()
````

````
{"reqId":"aH4xX1Xt4na5V3nDI3fv","level":3,"time":"2020-11-20T12:45:16+00:00","remoteAddr":"x.x.x.x","user":"admin.ch","app":"index","method":"POST","url":"/apps/occweb/cmd","message":{"Exception":"Exception","Message":"Return value of \"OCA\\GroupFolders\\Command\\ExpireGroupVersions::execute()\" must be of the type int, \"null\" returned.","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OCCWeb\\Controller\\OccController"},"cmd"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\OCCWeb\\Controller\\OccController","cmd",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"occweb.occ.cmd"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/occweb/cmd"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Return value of \"OCA\\GroupFolders\\Command\\ExpireGroupVersions::execute()\" must be of the type int, \"null\" returned.","Code":0,"Trace":[{"file":"/var/www/html/core/Command/Base.php","line":169,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"},{"__class__":"OCA\\OCCWeb\\Controller\\OccOutput"}]},{"file":"/var/www/html/custom_apps/mail/vendor/symfony/console/Application.php","line":920,"function":"run","class":"OC\\Core\\Command\\Base","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"},{"__class__":"OCA\\OCCWeb\\Controller\\OccOutput"}]},{"file":"/var/www/html/custom_apps/mail/vendor/symfony/console/Application.php","line":266,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"OCA\\GroupFolders\\Command\\ExpireGroupVersions"},{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"},{"__class__":"OCA\\OCCWeb\\Controller\\OccOutput"}]},{"file":"/var/www/html/custom_apps/mail/vendor/symfony/console/Application.php","line":142,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"},{"__class__":"OCA\\OCCWeb\\Controller\\OccOutput"}]},{"file":"/var/www/html/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"},{"__class__":"OCA\\OCCWeb\\Controller\\OccOutput"}]},{"file":"/var/www/html/custom_apps/occweb/lib/Controller/OccController.php","line":58,"function":"run","class":"OC\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"},{"__class__":"OCA\\OCCWeb\\Controller\\OccOutput"}]},{"file":"/var/www/html/custom_apps/occweb/lib/Controller/OccController.php","line":75,"function":"run","class":"OCA\\OCCWeb\\Controller\\OccController","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\StringInput"}]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"cmd","class":"OCA\\OCCWeb\\Controller\\OccController","type":"->","args":["groupfolders:expire"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OCCWeb\\Controller\\OccController"},"cmd"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\OCCWeb\\Controller\\OccController"},"cmd"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\OCCWeb\\Controller\\OccController","cmd",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"occweb.occ.cmd"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/occweb/cmd"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/mail/vendor/symfony/console/Command/Command.php","Line":261},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"20.0.2.2","id":"5fbbb132dd091"}
````

### PR DESCRIPTION
**Pull request by Chartman123**
Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

This fixes #1153 by adding return codes.

### CODE REVIEW

**Comment by Chartman123** [comment]
@juliushaertl Is there anything missing to get this merged?

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Nope, I just didn't see this before. Thanks a lot :+1:

**Comment by ChristophWurst** [comment]
Thanks and congrats to the accepted PR @Chartman123 :wink:

**Comment by Chartman123** [comment]
Thank you 😄

**Pull request merged**
