### PR TITLE
Support moving versions across storages

### PR DESCRIPTION
**Pull request by artonge**
As of https://github.com/nextcloud/server/pull/44187

One limitation is that when copying a folder from and to a groupfolder, versions of subfolders will be lost. This is due to the `NodeCopiedEvent` event not containing the list of moved files in subfolders. This needs to be addressed in the server.

Example: When moving `/a` containing `/a/b/c.txt` into `/d` which is a groupfolder, then `c.txt` will lose its versions because the `NodeCopiedEvent` does not contain the information that `c.txt` was copied. Weirdly, it works when moving a folder containing `/a/c.txt`.

The test exists and is disabled for now.

### CODE REVIEW

**Review by come-nc — APPROVED** [review]
Was moving from one groupfolders to another also tested?
And moving from groupfolder to folder?

**Comment by artonge** [comment]
> Was moving from one groupfolders to another also tested?

Out of the scope of this PR. This is only tackling folder to groupfolder move, and vis versa.

> And moving from groupfolder to folder?

Yes, both way.

**Comment by come-nc** [comment]
```
$ occ groupfolders:expire
Expiring version in 'Test'
An unhandled exception has been thrown:
TypeError: OCA\GroupFolders\Versions\VersionsBackend::getVersionFolderForFile(): Argument #1 ($file) must be of type OCP\Files\File, OC\Files\FileInfo given, called in /var/www/html/apps-extra/groupfolders/lib/Versions/VersionsBackend.php on line 92 and defined in /var/www/html/apps-extra/groupfolders/lib/Versions/VersionsBackend.php:78
Stack trace:
#0 /var/www/html/apps-extra/groupfolders/lib/Versions/VersionsBackend.php(92): OCA\GroupFolders\Versions\VersionsBackend->getVersionFolderForFile(Object(OC\Files\FileInfo))
#1 /var/www/html/apps-extra/groupfolders/lib/Versions/GroupVersionsExpireManager.php(81): OCA\GroupFolders\Versions\VersionsBackend->getVersionsForFile(Object(OC\User\User), Object(OC\Files\FileInfo))
#2 /var/www/html/apps-extra/groupfolders/lib/Versions/GroupVersionsExpireManager.php(60): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder(Array)
#3 /var/www/html/apps-extra/groupfolders/lib/Command/ExpireGroup/ExpireGroupVersions.php(66): OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
#4 /var/www/html/apps-extra/groupfolders/lib/Command/ExpireGroup/ExpireGroupVersionsTrash.php(54): OCA\GroupFolders\Command\ExpireGroup\ExpireGroupVersions->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\GroupFolders\Command\ExpireGroup\ExpireGroupVersionsTrash->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/core/Command/Base.php(177): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(1040): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\GroupFolders\Command\ExpireGroup\ExpireGroupVersionsTrash), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/console.php(113): OC\Console\Application->run()
#12 /var/www/html/occ(11): require_once('/var/www/html/c...')
#13 {main}⏎                                                      
```
@artonge There is a typing problem it seems?

**Pull request merged**
