### PR TITLE
Enforce string for folder id when obtaining the trash folder

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix for https://github.com/nextcloud/groupfolders/issues/907#issuecomment-821128558

### CODE REVIEW

**Review by acsfer — APPROVED** [review]
LGTM

**Comment by kesselb** [comment]
https://github.com/nextcloud/groupfolders/blob/6633e64d198c2b042dbee8072ba8f148ddcc2855/lib/Trash/TrashBackend.php#L270-L272

To use strict types later we may cast the folder id to a string here. However i'm a bit supprised to see $folderId as integer here as the value comes from the database and should be a string.

**Comment by fschrempf** [comment]
> However i'm a bit supprised to see $folderId as integer here as the value comes from the database and should be a string.

Looks like we already cast the id to int right after we get it from the db: 

https://github.com/nextcloud/groupfolders/blob/6e6d353754eab88c17c175942eef6d3380f3b73c/lib/Folder/FolderManager.php#L418

**Review by fschrempf — APPROVED** [review]
Casting the types back and forth (the folder id is originally a string when it is retrieved from the db) in several kind of places seems kind of messy, but cleaning this is out of scope of this PR.

**Comment by kesselb** [comment]
> Casting the types back and forth (the folder id is originally a string when it is retrieved from the db) in several places seems kind of messy, but cleaning this is out of scope of this PR.

In groupfolders it's okay to treat the folderId as integer. As soon as we use the folderId to access the filesystem the folderId must be a string (because the filesystem api expects a string). 

A string typehint for getTrashFolder tell's php to convert the method parameter to a string. But only if strict types are not enabled for the current file. The goal is to have more files with strict code. Adding a cast to string before calling the typed method ensures that the code still works with strict mode enabled. 

https://github.com/nextcloud/groupfolders/blob/6633e64d198c2b042dbee8072ba8f148ddcc2855/lib/Trash/TrashBackend.php#L270

`$folderId = (string)$folder['folder_id'];` and it will also work with strict mode.

**Comment by fschrempf** [comment]
> A string typehint for getTrashFolder tell's php to convert the method parameter to a string. But only if strict types are not enabled for the current file. The goal is to have more files with strict code. Adding a cast to string before calling the typed method ensures that the code still works with strict mode enabled.

Ok, sounds reasonable. But then it looks like there is at least one more case where `getTrashFolder()` is called with an int parameter. I guess this needs to be fixed, too:

https://github.com/nextcloud/groupfolders/blob/7d7abd6fa750d31d7afb8d284b58b513b6805b34/lib/Trash/TrashBackend.php#L323-L326

**Comment by kesselb** [comment]
Yep. As getTrashFolder is a groupfolder method it would also work to typehint the method to int and cast the string inside getTrashFolder.

**Comment by fschrempf** [comment]
@juliushaertl Could you improve this according to the suggestion from @kesselb? Thanks!

**Comment by andyxheli** [comment]
Anyway we can get this on the next release ?

**Comment by juliushaertl** [comment]
Adjusted accordingly to always use an int internally and only cast to string when referring to the nodes API.

I also added a cast to avoid possible further string occurences when building the folder array from the database results.

**Review by andyxheli — APPROVED** [review]

**Pull request merged**
