### PR TITLE
Display unsupported messages when trying to scan object store based group folder

### PR DESCRIPTION
**Pull request by CarlSchwan**
Since the group folder with an object store as primary storage are now
using an NoopScanner, the number of folders and files found is always
zero.

Signed-off-by: Carl Schwan <carl@carlschwan.eu>

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by PVince81** [comment]
> Since the group folder with an object store as primary storage are now
> using an NoopScanner, the number of folders and files found is always
> zero.
> 
> Signed-off-by: Carl Schwan [carl@carlschwan.eu](mailto:carl@carlschwan.eu)

great idea!

**Comment by juliushaertl** [comment]
/backport 2978a4be8eb97cfaf4d681f118e62921ae63d5a5 to stable22

**Comment by juliushaertl** [comment]
/backport 2978a4be8eb97cfaf4d681f118e62921ae63d5a5 to stable21

**Comment by juliushaertl** [comment]
/backport 2978a4be8eb97cfaf4d681f118e62921ae63d5a5 to stable20

**Pull request merged**
