### PR TITLE
fix(sidebar): Use icon slot for read-only ACL states

### PR DESCRIPTION
**Pull request by ChristophWurst**
1) Create a user
2) Create a group
3) Create a groupfolder
4) Assign the group
5) Log in as the user
6) Open the sharing sidebar tab of the groupfolder

| Before | After
|---|---|
|  Bildschirmfoto vom 2023-02-17 17-32-29 | Bildschirmfoto vom 2023-02-17 17-28-47 |
|---|---|

### CODE REVIEW

**Comment by nickvergessen** [comment]
If a NcButton does mot have a Text, it needs a title + aria-label 🥲
Browser console should tell that as a warning (I'd really like to see this moved to compile time if possible)

**Comment by ChristophWurst** [comment]
Fair enough. But that is irrelevant to the broken icons, isn't it?

**Comment by ChristophWurst** [comment]
> If a NcButton does mot have a Text, it needs a title + aria-label smiling_face_with_tear

https://github.com/nextcloud/groupfolders/pull/2271 :)

**Review by CarlSchwan — APPROVED** [review]

**Pull request merged**
