### PR TITLE
Fix quota bar appearance

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

fixes https://github.com/nextcloud/groupfolders/issues/2332

### CODE REVIEW

**Review by nimishavijay — CHANGES_REQUESTED** [review]
Looks great overall! For accessibility reasons, I would suggest that the text color be changed to `--color-main-text`, other than that it is very nice!

image

image

**Comment by Jerome-Herbinet** [comment]
> Looks great overall! For accessibility reasons, I would suggest that the text color be changed to `--color-main-text`, other than that it is very nice!
> 
> image
> 
> image

Done @nimishavijay :-)

**Pull request merged**
