### PR TITLE
Fix GF's ACL's field appearance

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Signed-off-by: Jérôme Herbinet <33763786+Jerome-Herbinet@users.noreply.github.com>

fixes https://github.com/nextcloud/groupfolders/issues/2331

Before : 

After :

### CODE REVIEW

**Comment by koelle25** [comment]
How does it look in the dark theme @Jerome-Herbinet? Can you try and post screenshots of this, too? Not that the fix messes it up the other way round.

**Comment by Jerome-Herbinet** [comment]
> How does it look in the dark theme @Jerome-Herbinet? Can you try and post screenshots of this, too? Not that the fix messes it up the other way round.

I'll check it and tell you what it does.

**Comment by Jerome-Herbinet** [comment]
> > How does it look in the dark theme @Jerome-Herbinet? Can you try and post screenshots of this, too? Not that the fix messes it up the other way round.
> 
> I'll check it and tell you what it does.

@koelle25, it's OK :

**Review by nimishavijay — APPROVED** [review]

**Comment by icewind1991** [comment]
I believe this is already fixed with https://github.com/nextcloud/groupfolders/pull/2335

**Comment by fschrempf** [comment]
Closing in favor of https://github.com/nextcloud/groupfolders/pull/2335 which is already merged.

**Pull request closed without merging**
