### PR TITLE
Adapt to server API changes

### PR DESCRIPTION
**Pull request by juliushaertl**
- fix: Adapt NoopScanner to renamed ObjectStoreScanner https://github.com/nextcloud/server/pull/37691
- fix: Adapt to new Folder interface method https://github.com/nextcloud/server/pull/37969

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by kesselb** [comment]
> PHP Fatal error:  Class OCA\GroupFolders\Helper\LazyFolder contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\Files\Folder::searchBySystemTag) in /var/www/html/apps-extra/groupfolders/lib/Helper/LazyFolder.php on line 32

Thanks :+1: 

occ upgrade greeted me with the above error today. It works fine with your patch applied.

**Review by kesselb — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Did this now get manually backported? @juliushaertl

**Comment by ChristophWurst** [comment]
/backport https://github.com/nextcloud/groupfolders/commit/42fb12ba06cc4b45d0afdac2f92433b1d246e8b0,98eded8,9130130 to stable27

**Comment by AndyScherzinger** [comment]
@ChristophWurst seems like the backport bot isn't willing to help us out with this one 😕

**Comment by juliushaertl** [comment]
Seems to have found its way to the stable27 branch already with https://github.com/nextcloud/groupfolders/pull/2423

**Pull request merged**
