### PR TITLE
[stable28] Drop need of user folder

### PR DESCRIPTION
**Pull request by artonge**
The versions are bound to the groupfolder and not the current user. So we can get the `File` object without the current user folder.
This helps in situations where no user is logged in, like background jobs.

Psalm errors already exist in stable28

### CODE REVIEW

**Comment by luka-nextcloud** [comment]
@artonge  It works well as I checked. Could you please fix the merge conflict?

**Comment by Chartman123** [comment]
@artonge I tried the changes on my NC27 instance. The original error disappeared, however, now I get another one:

`TypeError: OCA\GroupFolders\Versions\GroupVersion::__construct(): Argument #11 ($versionFile) must be of type OCP\Files\File, OC\Files\FileInfo given, called in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php on line 132`

**Comment by solracsf** [comment]
@Chartman123 please post comments at https://github.com/nextcloud/groupfolders/issues/2559 so everybody cand read it. Thanks !

**Comment by solracsf** [comment]
@artonge what about to previously check if the entity does not already exists?
Something like, L88:

```suggestion
if (!$this->groupVersionsMapper->exists($versionEntity) {
	$this->groupVersionsMapper->insert($versionEntity);
}
```

Couldn't it help with https://github.com/nextcloud/groupfolders/issues/2559#issuecomment-1855944032 ?

**Review by come-nc — APPROVED** [review]

**Comment by artonge** [comment]
> artonge what about to previously check if the entity does not already exists?

It would hide the reason `getVersionsForFileFromDB` fails :thinking:

**Comment by solracsf** [comment]
Can this be backported to 27?

**Pull request merged**
