### PR TITLE
Fix occ when files_trashbin is disabled

### PR DESCRIPTION
**Pull request by juliushaertl**
Otherwise loading the ITrashManager interface fails when injecting the TrashBackend. I'm open to more elegant suggestions on how to solve this, though there doesn't seem to be a way to register occ commands programmatically or I couldn't find it.

### CODE REVIEW

**Comment by juliushaertl** [comment]
@rullzer @icewind1991 :ping_pong: for review

**Comment by enoch85** [comment]
Tested and works!

**Review by enoch85 — APPROVED** [review]

**Comment by enoch85** [comment]
Without this fix, all updates to 20.0.1 are broken in the Nextcloud VM as it will break `occ` to run properly. 

I would really appreciate if this could get merged soon.

Thanks! :rocket:

**Comment by rullzer** [comment]
ah joy. we should move this trashbin management to core I think at some point. So we can just depend it is there. That it is then disabled is fine.

**Pull request merged**
