### PR TITLE
Show inherited acls

### PR DESCRIPTION
**Pull request by nenadalm**
This pr adds inherited advanced rules into the sidebar together with rules for current file. This allows seeing all advanced rules for the file with possibility of changing any rule (rule for current file will be changed in case inherited rule is shown).

~~When rule is removed in the ui, it is removed from the list and if it was inherited, it will be shown there again after reopening (maybe this should be changed somehow?).~~

### CODE REVIEW

**Comment by janpekar** [comment]
I recommend do not allow to delete permission, that is inherited.

**Comment by nenadalm** [comment]
> I recommend do not allow to delete permission, that is inherited.

I removed the confusing behaviour and now inherited rules cannot be removed. In case they're changed and changed rule is removed, inherited rule takes it's place in the ui.

**Comment by juliushaertl** [comment]
Thanks a lot for your pull request, looks good from a first quick view, but I'll make sure to give it a proper review and test later this week.

**Comment by juliushaertl** [comment]
This is a really nice enhancement. Now from a UX perspective I think it would make sense to still somehow indicate that the rule is shown because it is inherited from a parent node. cc @jancborchardt 

image

The group2 entry is fully inherited from the parent (same as user1, but user1 was added as an individual rule to the "Child" directory). I would propose to make sure that the permission icons also get the same opacity level in that case.

**Comment by nenadalm** [comment]
opacity fixed

**Comment by jancborchardt** [comment]
> I would propose to make sure that the permission icons also get the same opacity level in that case.

Yep, good proposal. @nenadalm thanks for the contribution and the adjustment! :)

**Comment by wiswedel** [comment]
so can this PR be approved and merged then, @juliushaertl?

**Comment by juliushaertl** [comment]
Let me rebase so we can get this in

**Comment by juliushaertl** [comment]
I've pushed a rebased version of this in https://github.com/nextcloud/groupfolders/pull/999 since i didn't have push access to your repo. Let me close this PR in favor of the new one then.

**Pull request closed without merging**
