### PR TITLE
test: Add tests for Listeners

### PR DESCRIPTION
**Pull request by provokateurin**
~~Not ready, need to test if my CI adjustments install circles properly for the unit tests.~~

### CODE REVIEW

**Comment by provokateurin** [comment]
No idea about the oracle tests failing, I didn't even touch those tests or anything related to them :cry:

**Review by come-nc — APPROVED** [review]
fine apart from failure

**Comment by provokateurin** [comment]
Failure due to https://github.com/nextcloud/circles/issues/1697 / https://github.com/nextcloud/server/pull/48361

**Comment by provokateurin** [comment]
Test will pass once https://github.com/nextcloud/circles/pull/1698 is merged.

**Pull request merged**
