### PR TITLE
fix: Adapt return type for Nextcloud 26

### PR DESCRIPTION
**Pull request by juliushaertl**
Changed in https://github.com/nextcloud/server/pull/36120

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by march42** [comment]
This fixes issue #2264 on my test instance and makes beta3 usable. @nursoda

**Comment by nursoda** [comment]
@march42 Thanks for the hint! I just verified, it also does fix the issue for me. After modifying the three files accordingly, and re-activating groupfolders, all works fine and I see no error messages in nextcloud.log.

**Review by come-nc — APPROVED** [review]

**Comment by nursoda** [comment]
In NC 26 beta4 I get errors again. I've documented them in my initial issue report #2264.

**Comment by come-nc** [comment]
> In NC 26 beta4 I get errors again. I've documented them in my initial issue report #2264.

Yes because there was no new release of groupfolders application yet.

**Pull request merged**
