### PR TITLE
Sidebar view: refresh ACL entries when fileInfo prop changes #1378

### PR DESCRIPTION
**Pull request by jngrb**
Details: in NC 21, the sidebar is not reloaded completely if a different
file is selected. Instead, just the props of an open sidebar view
are updated. So far, the ACL list not respond to a changed prop.
This is now changed, fixing the issue reported as #1378.

Signed-off-by: Jan Niklas Grieb (home) <jan.grieb@gmail.com>

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]
Works

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
