### PR TITLE
Chore/repair cs fix

### PR DESCRIPTION
**Pull request by zak39**
I fix the cs command and replace by ".php-cs-fixer.php" and I create check the cs fix for php in the github workflow.

### CODE REVIEW

**Review by vitormattos — APPROVED** [review]

**Review by nickvergessen — CHANGES_REQUESTED** [review]
Please add the cache file to .gitignore

**Comment by zak39** [comment]
> Please add the cache file to .gitignore

Hi @nickvergessen :slightly_smiling_face: 

Is this line not sufficient to ignore the cache file ? :thinking: 

https://github.com/nextcloud/groupfolders/blob/561986ac644af91bf3a6e99595c65ea1f6538fe6/.gitignore#L2

**Comment by nickvergessen** [comment]
Should be enough yes

**Comment by CarlSchwan** [comment]
Ping on this, it would be nice to have ;)

**Pull request merged**
