### PR TITLE
fix: Typing of new getVersionsForFile method

### PR DESCRIPTION
**Pull request by artonge**
Fix https://github.com/nextcloud/groupfolders/issues/2964

### CODE REVIEW

**Review by icewind1991 — APPROVED** [review]

**Comment by solracsf** [comment]
DCO block? 🐞

**Review by come-nc — APPROVED** [review]

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/groupfolders/pull/3022

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/groupfolders/pull/3023

**Pull request merged**
