### PR TITLE
Handle missing disk versions

### PR DESCRIPTION
**Pull request by artonge**
This PR is a palliative upon groupfolders failing to move versions correctly when a file is moved across storage.

1. Delete versions folder when we detect that the original file in the group folder is not there anymore.(`GroupVersionsExpireManager.php`)
2. Create the version folder before reading it (`VersionsBackend.php`).
3. Delete version entity in the DB if the disk counterpart does not exist (`VersionsBackend.php`).

Fix https://github.com/nextcloud/groupfolders/issues/2559

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by EDVB-Paulick** [comment]
When is this patch available in 28? We really need it.

Cheers

**Comment by artonge** [comment]
> When is this patch available in 28? We really need it.

If this is important to you, please get a subscription at Nextcloud :).

**Comment by EDVB-Paulick** [comment]
> > When is this patch available in 28? We really need it.
> 
> If this is important to you, please get a subscription at Nextcloud :).

You are right, we are working on this issue internally ... ;-)

**Pull request merged**
